**IMPORT TENSORFLOW**

In [1]:
import tensorflow as tf

**IMPORT DATASETS**

In [2]:
mnist = tf.keras.datasets.mnist
(Train_X, Train_Y), (Test_X, Test_Y) = mnist.load_data()
Train_X, Test_X = Train_X / 255.0, Test_X / 255.0 

11493376/11490434 [==============================] - 0s 0us/step


In [3]:
print(Train_X.shape)
print(Train_Y.shape)

(60000, 28, 28)
(60000,)


In [4]:
print(Test_X.shape)
print(Test_Y.shape)

(10000, 28, 28)
(10000,)


**CREATE MODEL**

In [5]:
model = tf.keras.models.Sequential([
                                    tf.keras.layers.Flatten(input_shape=(28, 28)),
                                    tf.keras.layers.Dense(128, activation='relu'),
                                    tf.keras.layers.Dropout(0.2),
                                    tf.keras.layers.Dense(10)                                    
])

In [6]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)
model.compile(optimizer='adam', loss=loss_fn, metrics=['accuracy'])

**TRAIN MODEL**
The more the "epochs", the more accurate it will be.

In [7]:
model.fit(Train_X, Train_Y, epochs=50)

Epoch 1/50
1875/1875 [==============================] - 4s 2ms/step - loss: 0.4827 - accuracy: 0.8623
Epoch 2/50
1875/1875 [==============================] - 3s 2ms/step - loss: 0.1520 - accuracy: 0.9557
Epoch 3/50
1875/1875 [==============================] - 3s 2ms/step - loss: 0.1038 - accuracy: 0.9685
Epoch 4/50
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0854 - accuracy: 0.9737
Epoch 5/50
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0730 - accuracy: 0.9774
Epoch 6/50
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0651 - accuracy: 0.9796
Epoch 7/50
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0525 - accuracy: 0.9834
Epoch 8/50
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0491 - accuracy: 0.9843
Epoch 9/50
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0470 - accuracy: 0.9848
Epoch 10/50
1875/1875 [==============================] - 3s 2ms/step - loss: 0.041

In [8]:
model.evaluate(Test_X, Test_Y)

313/313 [==============================] - 1s 1ms/step - loss: 0.1090 - accuracy: 0.9814


[0.10896465182304382, 0.9814000129699707]

In [9]:
predictions = model(Train_X[:1]).numpy()
predictions

array([[-53.979805, -34.790516, -33.730343,  15.625871, -97.19039 ,
         32.81124 , -55.103397, -38.011066, -34.371796, -14.266312]],
      dtype=float32)

In [10]:
tf.nn.softmax(predictions).numpy()

array([[2.0282789e-38, 4.3744993e-30, 1.2628709e-29, 3.4394425e-08,
        0.0000000e+00, 1.0000000e+00, 0.0000000e+00, 1.7468718e-31,
        6.6493296e-30, 3.5849127e-21]], dtype=float32)

**IMPORT IMAGE**

In [11]:
from PIL import Image
from IPython.display import display

In [12]:
pic0 = Image.open('pic0.bmp')
display(pic0)

**CONVERT IMAGE TO ARRAY**

In [13]:
import numpy as np
pic0 = np.resize(pic0, (28,28))
im2arr = np.array(pic0)
im2arr = im2arr.reshape(1,28,28)

**IMPLEMENT MODEL**

In [14]:
Pred_Y = model.predict(im2arr)
print(Pred_Y)

[[-9336.695  -1124.1628 -8704.091  -4902.5845  2759.377  -1818.7526
  -6896.232  -2930.2637 -2628.7822 -3449.9922]]


In [15]:
Prob_Y = tf.nn.softmax(Pred_Y).numpy()
print(Prob_Y)

[[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]]


**PRINT RESULT**

**Argmax** = Printing Array's Index with the **highest value**

In [16]:
Hat_Y = np.argmax(Pred_Y)
print("The number is : ", Hat_Y, "With the Prediction Value of : ", max(Pred_Y[0]), "and the Probability of : ", max(Prob_Y[0]) )

The number is :  4 With the Prediction Value of :  2759.377 and the Probability of :  1.0


In [17]:
pic1 = Image.open('pic1.bmp')
display(pic1)

In [18]:
import numpy as np
pic1 = np.resize(pic1, (28,28))
im2arr = np.array(pic1)
im2arr = im2arr.reshape(1,28,28)

In [19]:
Pred_Y = model.predict(im2arr)
print(Pred_Y)

[[-7142.0845  3541.2817 -3245.7446 -4089.7983 -3576.26   -8130.703
  -7453.9067   733.9093 -1504.1931 -6021.4536]]


In [20]:
Prob_Y = tf.nn.softmax(Pred_Y).numpy()
print(Prob_Y)

[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [21]:
Hat_Y = np.argmax(Pred_Y)
print("The number is : ", Hat_Y, "With the Prediction Value of : ", max(Pred_Y[0]), "and the Probability of : ", max(Prob_Y[0]) )

The number is :  1 With the Prediction Value of :  3541.2817 and the Probability of :  1.0


In [22]:
pic2 = Image.open('pic2.bmp')
display(pic2)

In [23]:
import numpy as np
pic2 = np.resize(pic2, (28,28))
im2arr = np.array(pic2)
im2arr = im2arr.reshape(1,28,28)

In [24]:
Pred_Y = model.predict(im2arr)
print(Pred_Y)

[[  5625.2964  -13145.382     -213.98933  -4722.8496   -5474.9062
   -8105.8823   -2065.6973   -5903.319    -5151.3965   -3785.5112 ]]


In [25]:
Prob_Y = tf.nn.softmax(Pred_Y).numpy()
print(Prob_Y)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [26]:
Hat_Y = np.argmax(Pred_Y)
print("The number is : ", Hat_Y, "With the Prediction Value of : ", max(Pred_Y[0]), "and the Probability of : ", max(Prob_Y[0]) )

The number is :  0 With the Prediction Value of :  5625.2964 and the Probability of :  1.0


In [27]:
pic3 = Image.open('pic3.bmp')
display(pic3)

In [28]:
import numpy as np
pic3 = np.resize(pic3, (28,28))
im2arr = np.array(pic3)
im2arr = im2arr.reshape(1,28,28)

In [29]:
Pred_Y = model.predict(im2arr)
print(Pred_Y)

[[ -5171.8306 -12026.03    -1760.9655  -3272.4983  -5738.7417  -6159.0396
  -11916.572    5009.0415  -6448.1562   -673.3128]]


In [30]:
Prob_Y = tf.nn.softmax(Pred_Y).numpy()
print(Prob_Y)

[[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]


In [31]:
Hat_Y = np.argmax(Pred_Y)
print("The number is : ", Hat_Y, "With the Prediction Value of : ", max(Pred_Y[0]), "and the Probability of : ", max(Prob_Y[0]) )

The number is :  7 With the Prediction Value of :  5009.0415 and the Probability of :  1.0


In [32]:
pic4 = Image.open('pic4.bmp')
display(pic4)

In [33]:
import numpy as np
pic4 = np.resize(pic4, (28,28))
im2arr = np.array(pic4)
im2arr = im2arr.reshape(1,28,28)

In [34]:
Pred_Y = model.predict(im2arr)
print(Pred_Y)

[[-6753.093  -6006.9355 -2338.3748   802.6687 -6566.834  -2006.4211
  -9437.753  -2160.6936  3671.0962 -1275.135 ]]


In [35]:
Prob_Y = tf.nn.softmax(Pred_Y).numpy()
print(Prob_Y)

[[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]]


In [36]:
Hat_Y = np.argmax(Pred_Y)
print("The number is : ", Hat_Y, "With the Prediction Value of : ", max(Pred_Y[0]), "and the Probability of : ", max(Prob_Y[0]) )

The number is :  8 With the Prediction Value of :  3671.0962 and the Probability of :  1.0


In [37]:
pic5 = Image.open('pic5.bmp')
display(pic5)

In [38]:
import numpy as np
pic5 = np.resize(pic5, (28,28))
im2arr = np.array(pic5)
im2arr = im2arr.reshape(1,28,28)

In [39]:
Pred_Y = model.predict(im2arr)
print(Pred_Y)

[[-5510.9126  3688.4614 -4045.7988 -3958.4785 -5685.753  -4790.7227
  -3167.6245 -1909.3865  -974.0767 -9595.026 ]]


In [40]:
Prob_Y = tf.nn.softmax(Pred_Y).numpy()
print(Prob_Y)

[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [41]:
Hat_Y = np.argmax(Pred_Y)
print("The number is : ", Hat_Y, "With the Prediction Value of : ", max(Pred_Y[0]), "and the Probability of : ", max(Prob_Y[0]) )

The number is :  1 With the Prediction Value of :  3688.4614 and the Probability of :  1.0


In [42]:
pic6 = Image.open('pic6.bmp')
display(pic6)

In [43]:
import numpy as np
pic6 = np.resize(pic6, (28,28))
im2arr = np.array(pic6)
im2arr = im2arr.reshape(1,28,28)

In [44]:
Pred_Y = model.predict(im2arr)
print(Pred_Y)

[[ -9465.6045  -4086.0332   7968.9316  -2438.021   -9729.185   -9370.361
  -14814.152   -1193.801  -10448.029  -19583.645 ]]


In [45]:
Prob_Y = tf.nn.softmax(Pred_Y).numpy()
print(Prob_Y)

[[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]]


In [46]:
Hat_Y = np.argmax(Pred_Y)
print("The number is : ", Hat_Y, "With the Prediction Value of : ", max(Pred_Y[0]), "and the Probability of : ", max(Prob_Y[0]) )

The number is :  2 With the Prediction Value of :  7968.9316 and the Probability of :  1.0


In [47]:
pic7 = Image.open('pic7.bmp')
display(pic7)

In [48]:
import numpy as np
pic7 = np.resize(pic7, (28,28))
im2arr = np.array(pic7)
im2arr = im2arr.reshape(1,28,28)

In [49]:
Pred_Y = model.predict(im2arr)
print(Pred_Y)

[[-11925.356    -1690.4038   -2575.2988     230.21034  -8993.615
   -8465.302   -14034.765     4410.278    -5997.854    -4379.4717 ]]


In [50]:
Prob_Y = tf.nn.softmax(Pred_Y).numpy()
print(Prob_Y)

[[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]


In [51]:
Hat_Y = np.argmax(Pred_Y)
print("The number is : ", Hat_Y, "With the Prediction Value of : ", max(Pred_Y[0]), "and the Probability of : ", max(Prob_Y[0]) )

The number is :  7 With the Prediction Value of :  4410.278 and the Probability of :  1.0


In [52]:
pic8 = Image.open('pic8.bmp')
display(pic8)

In [53]:
import numpy as np
pic8 = np.resize(pic8, (28,28))
im2arr = np.array(pic8)
im2arr = im2arr.reshape(1,28,28)

In [54]:
Pred_Y = model.predict(im2arr)
print(Pred_Y)

[[ -8442.924    6002.546   -5081.6367  -6638.1055  -3619.7197  -7573.907
   -7553.4556  -3528.1729  -3184.8596 -13472.825 ]]


In [55]:
Prob_Y = tf.nn.softmax(Pred_Y).numpy()
print(Prob_Y)

[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [56]:
Hat_Y = np.argmax(Pred_Y)
print("The number is : ", Hat_Y, "With the Prediction Value of : ", max(Pred_Y[0]), "and the Probability of : ", max(Prob_Y[0]) )

The number is :  1 With the Prediction Value of :  6002.546 and the Probability of :  1.0


In [57]:
pic9 = Image.open('pic9.bmp')
display(pic9)

In [58]:
import numpy as np
pic9 = np.resize(pic9, (28,28))
im2arr = np.array(pic9)
im2arr = im2arr.reshape(1,28,28)

In [59]:
Pred_Y = model.predict(im2arr)
print(Pred_Y)

[[-6589.927  -9540.1875 -2846.985  -6508.576  -7246.513   -342.9161
   6127.268  -8182.462  -2201.8347 -5620.4795]]


In [60]:
Prob_Y = tf.nn.softmax(Pred_Y).numpy()
print(Prob_Y)

[[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]]


In [61]:
Hat_Y = np.argmax(Pred_Y)
print("The number is : ", Hat_Y, "With the Prediction Value of : ", max(Pred_Y[0]), "and the Probability of : ", max(Prob_Y[0]) )

The number is :  6 With the Prediction Value of :  6127.268 and the Probability of :  1.0
